[workspace]
members = [
    "lib",
    "cli",
    "config"
]

[profile.release]
debug = false

[patch.crates-io]
zcash_note_encryption = { git = "https://github.com/zingolabs/librustzcash", rev = "25d4a04bacfe2df4f3aa7a80862a539f79040d89" }
zcash_primitives = { git = "https://github.com/zingolabs/librustzcash", rev = "25d4a04bacfe2df4f3aa7a80862a539f79040d89" }
