[workspace]
members = [
    "lib",
    "cli",
    "config"
]

[profile.release]
debug = false

[patch.crates-io]
zcash_note_encryption = { git = "https://github.com/zingolabs/librustzcash", rev = "7e76a9983fe4719d9055b934e7316fb63273ce5a" }
zcash_primitives = { git = "https://github.com/zingolabs/librustzcash", rev = "7e76a9983fe4719d9055b934e7316fb63273ce5a" }
