[workspace]
members = [
    "lib",
    "cli",
    "config"
]

[profile.release]
debug = false

[patch.crates-io]
zcash_note_encryption = { git = "https://github.com/zingolabs/librustzcash", rev = "48bf54f0d080a97c8a506ec999148ae9d46e577a" }
zcash_primitives = { git = "https://github.com/zingolabs/librustzcash", rev = "48bf54f0d080a97c8a506ec999148ae9d46e577a" }
