[workspace]
members = [
    "lib",
    "cli",
    "config"
]

[profile.release]
debug = false

[patch.crates-io]
zcash_note_encryption = { git = "https://github.com/zingolabs/librustzcash", rev = "975a31754d01ffde666ce19a7126041c0261a290" }
zcash_primitives = { git = "https://github.com/zingolabs/librustzcash", rev = "975a31754d01ffde666ce19a7126041c0261a290" }
