[package]
name = "zingo-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
zingo-netutils = { path = "../zingo-netutils" }

zcash_client_backend.workspace = true
zcash_primitives.workspace = true

futures.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing = "0.1.40"
