name: Main

on: 
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  Test:
    runs-on:                    ubuntu-22.04
    env:
      RUSTFLAGS:                -D warnings
    container:
      image:                    zingodevops/ci-build:stable
      options:                  --security-opt seccomp=unconfined
    steps:
      - name:                   Checkout repository
        uses:                   actions/checkout@v2
      - name:                   Symlink lightwalletd and zcash binaries
        run:                    ln -s /usr/bin/lightwalletd /usr/bin/zcashd /usr/bin/zcash-cli ./regtest/bin/
      - name:                   Symlink zcash parameters
        run:                    ln -s /root/.zcash-params /github/home
      - name:                   Set cargo paths
        run: |
          CARGO_HOME=/usr/local/cargo
          CARGO_TARGET_DIR=/usr/local/build/target
          SCCACHE_DIR=/usr/local/sccache
          RUSTUP_HOME=/root/.rustup
      - name:                   Check formatting of code
        run:                    cargo fmt --check
      - name:                   Generate code coverage
        run:
          cargo tarpaulin --all-features --verbose --workspace --avoid-cfg-tarpaulin --skip-clean --ignore-tests --release --timeout 300 --out xml
      - name:                   Upload to codecov.io
        uses:                   codecov/codecov-action@v2
        with:
          fail_ci_if_error:     true
